name: Selenium Screenshot Test

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Chromium and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        echo "Chromium and Chromedriver installed"

    - name: Set environment for Chrome
      run: |
        which chromedriver
        which chromium-browser

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Take screenshot
      env:
        CHROME_BINARY: /usr/bin/chromium-browser
      run: python selenium_test.py

    - name: Commit screenshot to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add screenshot.png
        git commit -m "Add screenshot"
        git push
