name: Selenium Screenshot Test

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin

    - name: Take screenshot
      run: python selenium_test.py

    - name: Commit screenshot to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add screenshot.png
        git commit -m "Add screenshot"
        git push
